apiVersion: apps.kruise.io/v1alpha1
kind: CloneSet
metadata:
  labels:
    app: nginx-cloneset
  name: nginx-cloneset
spec:
  replicas: 5
  selector:
    matchLabels:
      app: nginx-cloneset
  template:
    metadata:
      labels:
        app: nginx-cloneset
    spec:
      containers:
      - name: nginx-cloneset
        image: registry.cn-beijing.aliyuncs.com/zhengyansheng/nginx:v1.0 
  updateStrategy:
    partition: 2
    # type: InPlaceOnly  # ReCreate | InPlaceIfPossible
    # maxUnavailable: 1
    # maxSurge: 0

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-cloneset 
spec:
  type: ClusterIP
  selector:
    app: nginx-cloneset 
  ports:
    - port: 80
      targetPort: 80

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-cloneset 
spec:
  rules:
  - host: xxx.local 
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nginx-cloneset 
            port:
              number: 80
