kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-01 
spec:
  storageClassName: managed-nfs-storage
  accessModes: # 策略
    - ReadWriteMany
  resources: 
    requests:
      storage: 10Mi # 请求空间大小
