apiVersion: kubescheduler.config.k8s.io/v1
kind: KubeSchedulerConfiguration
clientConnection:
  kubeconfig: "/etc/kubernetes/scheduler.conf"
algorithmSource:
  policy:
    file:
      path: "/etc/kubernetes/scheduler-extender-policy.yaml"
leaderElection:
    leaderElect: true
    resourceLock: configmaps
    resourceNamespace: kube-system
    resourceName: kube-scheduler
    leaseDuration: 15
    renewDeadline: 10
    retryPeriod: 2
    schedulerName: random-scheduler
extenders:
    - urlPrefix: "http://127.0.0.1:8888/"
      filterVerb: "filter"
      prioritizeVerb: "prioritize"
      weight: 1
      enableHttps: false
      nodeCacheCapable: false

