apiVersion: apps.zhengyansheng.com/v1
kind: Nginx
metadata:
  labels:
    app.kubernetes.io/name: nginx
    app.kubernetes.io/instance: nginx-sample
    app.kubernetes.io/part-of: nginx-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: nginx-operator
  name: nginx-sample
  namespace: default
spec:
  # TODO(user): Add fields here
  replicas: 2
  image: "nginx:latest"
