apiVersion: apps/v1
kind: Deployment
metadata:
  name: shark-canary
  labels:
    app: shark
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shark
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: shark
        version: v2.0
    spec:
      containers:
        - name: shark
          image: zhengyscn/nginx:v2.0
          imagePullPolicy: IfNotPresent
