apiVersion: apps/v1
kind: Deployment
metadata:
  name: shark-canary
  labels:
    app: shark-canary
spec:
  replicas: 3
  selector:
    matchLabels:
      app: shark-canary
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: shark-canary
    spec:
      containers:
        - name: shark-canary
          image: zhengyscn/nginx:v2.0
          imagePullPolicy: IfNotPresent

---
apiVersion: v1
kind: Service
metadata:
  name: shark-canary
spec:
  type: ClusterIP
  selector:
    app: shark-canary
  ports:
    - port: 80
      targetPort: 80

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: shark-canary
  annotations:
    nginx.ingress.kubernetes.io/canary: "true"
    nginx.ingress.kubernetes.io/canary-weight: "10"  # 10% 流量发送到 v2
    nginx.ingress.kubernetes.io/canary-by-header: X-Canary
    nginx.ingress.kubernetes.io/canary-by-header-value: "true"
spec:
  rules:
  - host: www.guiyin.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: shark-canary
            port:
              number: 80
