apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: default
  name: random-scheduler
  labels:
    app: random-scheduler
    component: random-scheduler
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: random-scheduler
subjects:
  - kind: ServiceAccount
    name: random-scheduler
    namespace: default
roleRef:
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
  name: system:kube-scheduler