apiVersion: apps.kruise.io/v1alpha1
kind: CloneSet
metadata:
  labels:
    app: my-cloneset
  name: my-cloneset
spec:
  scaleStrategy:
    podsToDelete:
      - my-cloneset-lbvgr
  replicas: 3
  selector:
    matchLabels:
      app: my-cloneset
  template:
    metadata:
      labels:
        app: my-cloneset
    spec:
      containers:
        - name: nginx
          image: nginx:alpine