apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: istiogateway-sample
spec:
  rules:
  - http:
      paths:
      - backend:
          service:
            name: istio-ingressgateway 
            port:
              number: 80
        path: /
        pathType: Prefix
